name: Tag

on:
  push:
    tags:
      - '@livepeer/react@**'
  workflow_dispatch:

jobs:
  release:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to lvpr.tv
        run: curl -X POST -d {} $VERCEL_LVPR_DEPLOY_URL
        env:
          VERCEL_LVPR_DEPLOY_URL: ${{ secrets.VERCEL_LVPR_DEPLOY_URL }}
